title = 'Heron'
baseURL = "/"
themesDir = "themes"
theme = "hugo-whisper-theme"
languageCode = "en-us"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 3


[params]
  homepage_button_link = '/about'
  homepage_button_text = 'Learn more about Heron'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = false

  [params.homepage_meta_tags]
    meta_description = "Heron is not a privacy app. Heron is a transparency app."
    meta_og_title = "Heron"
    meta_og_type = "app"
    meta_og_url = "https://heron.mobi"
    meta_og_image = "!TODO"
    meta_og_description = "Heron is not a privacy app. Heron is a transparency app."
    meta_twitter_card = "Heron App"
    meta_twitter_site = "@HeronMobi"
    meta_twitter_creator = "@HeronMobi"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"

  [params.footer]
    copyright_text = ''
