AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CertARN:
    Type: String
  DomainName:
    Type: String
  HostedZone:
    Type: String
Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      CorsConfiguration:
        CorsRules:
        - AllowedMethods: 
            - GET
            - HEAD
          AllowedOrigins: 
            - "*"
          AllowedHeaders: 
            - "*"
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 's3:GetObject'
            Principal: "*" 
            Resource: !Sub '${WebsiteBucket.Arn}/*'
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig:
        Comment: "CDN S3 Access"
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
          - !Join
              - '.' 
              - - 'www'
                - !Ref DomainName
        DefaultRootObject: index.html
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 404
          ResponsePagePath: /404.html
        - ErrorCode: 404
          ResponseCode: 404
          ResponsePagePath: /404.html
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref CertARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
          TargetOriginId: !Sub "${WebsiteBucket}.s3.amazonaws.com"
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Origins:
        - CustomOriginConfig: 
            OriginProtocolPolicy: http-only
            HTTPPort: 80
            OriginSSLProtocols: 
              - TLSv1
              - TLSv1.1
              - TLSv1.2
            HTTPSPort: 443
          DomainName:  !Sub '${WebsiteBucket}.s3-website.${AWS::Region}.amazonaws.com'
          Id: !Sub "${WebsiteBucket}.s3.amazonaws.com"
        PriceClass: PriceClass_100
  DNSRecordSets:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
        - Name: 
            !Join
              - '.' 
              - - 'www'
                - !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt Distribution.DomainName
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt Distribution.DomainName
Outputs:
  WebsiteBucket:
    Value: !Ref WebsiteBucket
