AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CertARN:
    Type: String
  DomainName:
    Type: String
  HostedZone:
    Type: String
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: !Ref WebsiteBucket
        Version: '2012-10-17'
        Statement:
          - Sid: CloudfrontGet
            Action: s3:GetObject
            Effect: Allow
            Principal:
              AWS:
                !Join
                  - ""
                  - - "arn:"
                    - !Ref AWS::Partition
                    - ":iam::cloudfront:user/CloudFront Origin Access Identity "
                    - !Ref OriginAccessIdentity
            Resource:
              !Join
                - ""
                - - !GetAtt WebsiteBucket.Arn
                  - /*
          - Sid: AllowSSLRequestsOnly
            Action: s3:*
            Effect: Deny
            Resource:
              - !Sub "arn:aws:s3:::${WebsiteBucket}"
              - !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Principal: "*"
      Bucket: !Ref WebsiteBucket      
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: HeronWebsite
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Join
            - '.' 
            - - 'www'
              - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertARN
          SslSupportMethod: sni-only
        Comment: Website
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 60
          ForwardedValues:
            Headers: []
            QueryString: true
          TargetOriginId: websitesite
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: websitesite
            DomainName: !Sub ${WebsiteBucket}.s3.${AWS::Region}.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity.Id}
        PriceClass: PriceClass_100
  DNSRecordSets:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZone
      RecordSets:
        - Name: 
            !Join
              - '.' 
              - - 'www'
                - !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt Distribution.DomainName
Outputs:
  WebsiteBucket:
    Value: !Ref WebsiteBucket
